version: '3.3'

services:
  app:
    build: .
    #platform: linux/x86_64
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - database
      - redis
    env_file:
      - .env

  database:
    image: postgres
    container_name: database_gov_dev
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_gov_dev
    volumes:
      - pgdata:/data/postgres

  redis:
    image: bitnami/redis:7.0.5-debian-11-r3
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: governanca
    volumes:
      - redis:/bitnami/redis/data
    networks:
      - redis
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
